name: example
on: push
jobs:
  greeting:
    runs-on: ubuntu-latest
    steps:
      - name: first step
        run: echo hello world
  build_skim:
    runs-on: ubuntu-latest
    steps: 
      - name: executable compilation
        run: |
          COMPILER=$(root-config --cxx)
          $COMPILER -g -O3 -Wall -Wextra -Wpedantic -o skim skim.cxx